spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: phoneshop
    password: phoneshop2001
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


# Testing H2
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#  h2:
#    console.enabled: true

