spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: phoneshop
    password: phoneshop2001
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

